In [3]:
from implicit.evaluation import *
from implicit.als import AlternatingLeastSquares as ALS 
from implicit.bpr import BayesianPersonalizedRanking as BPR 
import scipy 
import numpy as np 

In [4]:
R = scipy.sparse.csr_matrix(np.array([[0, 3, 2], [5, 1, 2], [4, 2, 1], [2, 0, 4]]))

In [5]:
als_model = ALS(factors = 2, regularization=0.01, iterations=10)
als_model.fit(R.T)

100%|██████████| 10/10 [00:00<00:00, 200.55it/s]


In [6]:
np.dot(als_model.user_factors, als_model.item_factors.T)

array([[0.16591905, 1.0711838 , 0.8571768 ],
       [0.9712274 , 0.78086764, 1.1422706 ],
       [0.9634731 , 0.9120823 , 1.2301841 ],
       [1.1123229 , 0.31423268, 0.8987046 ]], dtype=float32)

In [7]:
print('user factors')
print(als_model.user_factors)

print('\n item factors')
print(als_model.item_factors.T)

user factors
[[2.011443  2.3077452]
 [3.8012543 2.3214183]
 [3.9705389 2.5829997]
 [3.5109692 1.4764923]]

 item factors
[[ 0.45240343 -0.16686188  0.15749823]
 [-0.3224206   0.6096067   0.23415847]]
